
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS artist_fee_type TEXT DEFAULT 'fixed';
ALTER TABLE events ADD COLUMN IF NOT EXISTS artist_fee_percent NUMERIC DEFAULT 0;
